###Get All Products
GET http://localhost:3003/products

###Create new Product
POST http://localhost:3003/products
Content-Type: application/json

{
  "id": "p004",
  "name": "Teclado",
  "price": 2500
}

###Edit a Product
PUT http://localhost:3003/products/p003
Content-Type: application/json

{
  "price": 3000
}

###Delete a Product
DELETE http://localhost:3003/products/p004
